/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package designpattterns;

public class App {

    public static void main(String[] args) {
        var mailService = new MailService();
        mailService.sendEmail();
    }
}
